language: python
python:
  - "2.7"
  - "3.5"
sudo: required
install:
  - "sudo apt-get install gfortran python-liblas libblas-dev liblapack-dev libatlas-dev"
  - "pip install -r requirements.txt"
script:
  - cd $HOME/build/edublancas/sklearn-evaluation/sklearn_evaluation/tests
  - ./run_tests