# python versions available:
# https://docs.travis-ci.com/user/languages/python/#specifying-python-versions

language: python
sudo: required
install:
  # CONDA INSTALL STARTS
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # CONDA INSTALL ENDS

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

script:
  - pip install nox
  - nox
  # freetype version must match for image comparison to work without issues
  # matplotlib 3.0.3 was built using freetype 2.6.1, travis has a lower version
  # but still works
  - freetype-config --ftversion

# report testing coverage on coveralls
after_success: coveralls