[tool.pkgmt]
github = "ploomber/sklearn-evaluation"
package_name = "sklearn_evaluation"
env_name = "ske"

[tool.pkgmt.check_links]
extensions = ["md", "rst", "py", "ipynb"]
ignore_substrings = ["sklearn-evaluation/tarball"]

[tool.nbqa.addopts]
flake8 = [
    # notebooks allow non-top imports
    "--extend-ignore=E402",
]
