title: sklearn-evaluation
author: Ploomber
copyright: Ploomber
logo: logo.jpeg

# https://jupyterbook.org/en/stable/structure/configure.html#disable-building-files-that-arent-in-the-table-of-contents
# some of our example notebooks download new notebooks, to exclude them
# from execution, we turn on this flag
only_build_toc_files: true

execute:
  execute_notebooks: cache
  timeout: 120
  # some notebooks download files, so we run them in a tmp
  # directory to clean everything up
  run_in_temp: true

sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.napoleon
    - sphinx.ext.autosummary
    - sphinx.ext.intersphinx
    - matplotlib.sphinxext.plot_directive


  config:
    html_show_copyright: True
    plot_include_source: True
    plot_html_show_formats: False
    plot_html_show_source_link: False
    intersphinx_mapping:
      sklearn:
        - "http://scikit-learn.org/stable"
        - null
      matplotlib:
        - "http://matplotlib.org/"
        - null
    execution_allow_errors: True
    execution_timeout: 1000
    suppress_warnings: ['myst.domains', 'myst.header']
    exclude_patterns: ['README.md']


# # Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib


repository:
  url: https://github.com/ploomber/sklearn-evaluation
  path_to_book: docs
  branch: master

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: Join us on <a href="https://ploomber.io/community/">Slack!</a>
  announcement: To launch any tutorial in JupyterLab, click on the ðŸš€ button below!

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://binder.ploomber.io"
