title: sklearn-evaluation
author: Ploomber
logo: logo.png
execute:
  execute_notebooks: force
sphinx:
  extra_extensions:
    - 'matplotlib.sphinxext.plot_directive'
    - 'IPython.sphinxext.ipython_console_highlighting'
    - 'IPython.sphinxext.ipython_directive'
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.autosummary'
    - 'sphinx.ext.intersphinx'
    - 'sphinx.ext.napoleon'

# Define the name of the latex output file for PDF builds
# latex:
#   latex_documents:
#     targetname: book.tex

# # Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# # Information about where the book exists on the web
# repository:
#   url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#   path_to_book: docs  # Optional path to your book, relative to the repository root
#   branch: master  # Which branch of the repository should be used when creating links (optional)

# # Add GitHub buttons to your book
# # See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
# html:
#   use_issues_button: true
#   use_repository_button: true
